"""initial migration

Revision ID: f195c530d280
Revises: 6e597a4684c8
Create Date: 2025-03-29 20:51:24.521667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f195c530d280'
down_revision = '6e597a4684c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('plaid_access_token', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('category_limits', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('remaining_balance', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('minimum_payment', sa.Float(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('debt_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_achieved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('plaid_transaction_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_amount', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('transactions')
    op.drop_table('goals')
    op.drop_table('debts')
    op.drop_table('budgets')
    op.drop_table('users')
    # ### end Alembic commands ###
